### ISSUE TITLE
numpy 1.24: AttributeError: module 'numpy' has no attribute 'int'

### ISSUE THREAD

**Issue by elizagamedev** [kha-white/mokuro#38]
I think there was a breaking change in numpy 1.24.

```
  File "/usr/local/lib/python3.10/dist-packages/comic_text_detector/utils/db_utils.py", line 200, in box_score_fast
    xmin = np.clip(np.floor(box[:, 0].min()).astype(np.int), 0, w - 1)
           │  │    │  │     │                       │           └ 1024
           │  │    │  │     │                       └ <module 'numpy' from '/usr/local/lib/python3.10/dist-packages/numpy/__init__.py'>
           │  │    │  │     └ array([[ 752,  999],
           │  │    │  │              [ 753,  999],
           │  │    │  │              [ 754, 1000],
           │  │    │  │              [ 755, 1000],
           │  │    │  │              [ 756, 1001],
           │  │    │  │              [ 755, 1000],...
           │  │    │  └ <ufunc 'floor'>
           │  │    └ <module 'numpy' from '/usr/local/lib/python3.10/dist-packages/numpy/__init__.py'>
           │  └ <function clip at 0x7fbe149ea8c0>
           └ <module 'numpy' from '/usr/local/lib/python3.10/dist-packages/numpy/__init__.py'>
  File "/usr/local/lib/python3.10/dist-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "

AttributeError: module 'numpy' has no attribute 'int'
```

Installing version 1.23.0 instead of 1.24.0 of numpy works instead.

**Comment by kha-white** [comment]
Fixed in 0.1.6, it works with numpy 1.24 now
